"""add skill planning fields

Revision ID: f1c4264a44bc
Revises: 
Create Date: 2026-05-07 15:42:43.354817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1c4264a44bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'conversations', 'skills', ['skill_id'], ['id'])
    op.drop_column('knowledge_bases', 'milvus_collection')
    op.add_column('skills', sa.Column('planning_mode', sa.String(length=20), server_default='auto', nullable=False))
    op.add_column('skills', sa.Column('confirm_plan', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('skills', sa.Column('confirm_tools', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'confirm_tools')
    op.drop_column('skills', 'confirm_plan')
    op.drop_column('skills', 'planning_mode')
    op.add_column('knowledge_bases', sa.Column('milvus_collection', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    # ### end Alembic commands ###
